version: '3.8'

services:
  mem0-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mem0-api-server-master
    env_file:
      - .env
    # ports:
    #   - "${PORT}:8000"
    network_mode: host
    volumes:
      - .:/workspace
    # networks:
    #   - robot-ai-workflow-network-master
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 6699 --workers ${WORKERS}

# networks:
#   robot-ai-workflow-network-master:
#     driver: bridge